Fix openshot's launcher (Exec=)
NOTE, the AppImage does not works for me, I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/Console.py", line 37, in run
  File "openshot_qt/launch.py", line 55, in <module>
    from PyQt5.QtWidgets import QApplication
ImportError: /tmp/.mount_openshxr5s0R/usr/bin/libm.so.6: version `GLIBC_2.35' not found (required by /lib/x86_64-linux-gnu/libharfbuzz.so.0)
```

Consider rollback using the new --rollback option